name: myapp
description: "Peaky Fitness App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Images register ho gayi
  assets:
    - assets/images/dumbbell_bg.png
    - assets/images/arrow_up.png

  # Font register ho gaya
  fonts:
    - family: PeakyFont
      fonts:
        - asset: assets/fonts/PeakyFont.otf
